Bump quarkus.version from 3.30.2 to 3.30.4 (#132)
Bumps `quarkus.version` from 3.30.2 to 3.30.4.
Updates `io.quarkus:quarkus-bom` from 3.30.2 to 3.30.4
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-bom's
releases</a>.</em></p>
<blockquote>
<h2>3.30.4</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50814">#50814</a>
- Changing compose-devservices.yml does not invalidate Gradle cache</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51045">#51045</a>
- Port 8080 already used using quarkus-amazon-lambda and
quarkus-observability-devservices-*</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51107">#51107</a>
- JBoss Threads update to version 3.9.2, allows minor cleanup</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51139">#51139</a>
- Upgrade LGTM to 0.11.17</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51326">#51326</a>
- Running <code>mvn dependency:tree quarkus:dev</code> gives
<code>[WARNING] Failed to locate plugin for dependency:tree</code></li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51363">#51363</a>
- Bump to Mutiny 3.1.0 and Mutiny Vert.x bindings 3.21.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51481">#51481</a>
- Make sure collected managed dependencies do not include
duplicates</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51485">#51485</a>
- Unable to build: Quarkus ChainBuildException due to JFR
dependency</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51488">#51488</a>
- Remove warning failing to determine the build plugin prefix</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51494">#51494</a>
- Qute message bundles: fix msg:message with single param</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51497">#51497</a>
- Include compose files for Dev Services as test task's inputs</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51504">#51504</a>
- OIDC issuer based resolution does not work for local tenants</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51524">#51524</a>
- Break build cycle between gRPC and JFR extensions</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51528">#51528</a>
- Update RESTEasy to 6.2.15.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51539">#51539</a>
- Remove unneeded vertx-http, upgrade LGTM image</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51547">#51547</a>
- Fix issuer-based tenant resolution for a tenant issuer configured in
OIDC tenant configuration rather than well-known configuration</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51567">#51567</a>
- Bump to Vert.x 4.5.23 and Netty 4.1.130.Final</li>
</ul>
<h2>3.30.3</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50298">#50298</a>
- Call to the
<code>jakarta.data.repository.BasicRepository#saveAll</code> results in
NPE after Hibernate ORM bump to 7.1.1.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50919">#50919</a>
- Java classes generated by <code>wsdl2java</code> not passed to Gradle
<code>compileKotlin</code> since 3.26.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51044">#51044</a>
- JavaDoc not rendering correctly</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51290">#51290</a>
- Add cross-references between CSRF and CORS filter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51339">#51339</a>
- Enhance error message when
quarkus.hibernate-search-orm.management.enabled=true is enabled but no
quarkus-vertx-http defined</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51340">#51340</a>
- Fix JavaDoc for quarkus.management.enabled</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51341">#51341</a>
- Use correct name for <code>org.graalvm.sdk:nativebridge</code>
dependency</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51344">#51344</a>
- Set expiresIn to one hour for OIDC Dev Services</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51345">#51345</a>
- extraneous semicolon in LGTM starter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51346">#51346</a>
- Bump the hibernate group with 9 updates</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51352">#51352</a>
- Bump org.quartz-scheduler:quartz from 2.5.0 to 2.5.2</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51358">#51358</a>
- Bump Keycloak version to 26.4.7</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51361">#51361</a>
- Remove extraneous semicolon in LGTM codestart</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51370">#51370</a>
- Add documentation about <code>@JsonView</code> support in the REST
Client</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51372">#51372</a>
- Make token expiration configurable for OIDC Dev Services</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51375">#51375</a>
- Config relocation mp.messaging -&gt; quarkus.messaging
relocation/fallback</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51376">#51376</a>
- Bump kafka.version from 4.0.1 to 4.1.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51377">#51377</a>
- Enhance docs for quarkus.debug.reflection option</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51378">#51378</a>
- QuarkusComponentTest fails with ambiguous dependencies if bean is
injected with parameterized qualifier multiple times</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51379">#51379</a>
- Check that Vert.x HTTP is available before enabling Hibernate Search
management endpoints</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51380">#51380</a>
- Clear some internal state of REST Assured between tests</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51394">#51394</a>
- Make container-image.tag optional so it is possible to nullify it</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51399">#51399</a>
- Fix LogRuntimeConfig doc rendering</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51408">#51408</a>
- Lambda extension: Failed to start quarkus because of
NoSuchMethodError</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/27d19efa3fc61601205bdef56123862e29ef8566"><code>27d19ef</code></a>
[RELEASE] - Bump version to 3.30.4</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/e3f096fb3cf74bebc7eb4ff220c95480a3309f04"><code>e3f096f</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/51588">#51588</a>
from gsmet/3.30.4-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/a229f483aee508b81268c12357e445ceba990985"><code>a229f48</code></a>
Bump to Vert.x 4.5.23 and Netty 4.1.130.Final</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/ea8b668466095ba0753067145c120dbf59d5d34a"><code>ea8b668</code></a>
Bump to Mutiny 3.1.0 and Mutiny Vert.x bindings 3.21.1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/993f47f644c629cb30f5589f3dfce1a631acbb72"><code>993f47f</code></a>
No longer need to disable JBoss Threads logging of version</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/51b52ebd6bad8f75bd190e3800874cfec3411e2c"><code>51b52eb</code></a>
Upgrade to JBoss Threads 3.9.2</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/eba293febde2c943bd64d0363b749b777e8ff1e9"><code>eba293f</code></a>
feat(oidc): fix issuer-based tenant resulition for local issuers</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/80a9a9b8e3e3866ee8f994479b08566e4244e61a"><code>80a9a9b</code></a>
Remove unneeded vertx-http.</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/878e383f416dabe4f5a1ed791e9fe1983f4f911b"><code>878e383</code></a>
Upgrade LGTM to 0.11.17</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/61766a77f60f10a86220188fa7017eee070694bc"><code>61766a7</code></a>
Update RESTEasy to 6.2.15.Final</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.30.2...3.30.4">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.quarkus:quarkus-maven-plugin` from 3.30.2 to 3.30.4

Updates `io.quarkus:quarkus-config-doc-maven-plugin` from 3.30.2 to
3.30.4

Updates `io.quarkus:quarkus-extension-processor` from 3.30.2 to 3.30.4

Updates `io.quarkus:quarkus-extension-maven-plugin` from 3.30.2 to
3.30.4
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-extension-maven-plugin's
releases</a>.</em></p>
<blockquote>
<h2>3.30.4</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50814">#50814</a>
- Changing compose-devservices.yml does not invalidate Gradle cache</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51045">#51045</a>
- Port 8080 already used using quarkus-amazon-lambda and
quarkus-observability-devservices-*</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51107">#51107</a>
- JBoss Threads update to version 3.9.2, allows minor cleanup</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51139">#51139</a>
- Upgrade LGTM to 0.11.17</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51326">#51326</a>
- Running <code>mvn dependency:tree quarkus:dev</code> gives
<code>[WARNING] Failed to locate plugin for dependency:tree</code></li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51363">#51363</a>
- Bump to Mutiny 3.1.0 and Mutiny Vert.x bindings 3.21.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51481">#51481</a>
- Make sure collected managed dependencies do not include
duplicates</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51485">#51485</a>
- Unable to build: Quarkus ChainBuildException due to JFR
dependency</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51488">#51488</a>
- Remove warning failing to determine the build plugin prefix</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51494">#51494</a>
- Qute message bundles: fix msg:message with single param</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51497">#51497</a>
- Include compose files for Dev Services as test task's inputs</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51504">#51504</a>
- OIDC issuer based resolution does not work for local tenants</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51524">#51524</a>
- Break build cycle between gRPC and JFR extensions</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51528">#51528</a>
- Update RESTEasy to 6.2.15.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51539">#51539</a>
- Remove unneeded vertx-http, upgrade LGTM image</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51547">#51547</a>
- Fix issuer-based tenant resolution for a tenant issuer configured in
OIDC tenant configuration rather than well-known configuration</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51567">#51567</a>
- Bump to Vert.x 4.5.23 and Netty 4.1.130.Final</li>
</ul>
<h2>3.30.3</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50298">#50298</a>
- Call to the
<code>jakarta.data.repository.BasicRepository#saveAll</code> results in
NPE after Hibernate ORM bump to 7.1.1.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50919">#50919</a>
- Java classes generated by <code>wsdl2java</code> not passed to Gradle
<code>compileKotlin</code> since 3.26.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51044">#51044</a>
- JavaDoc not rendering correctly</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51290">#51290</a>
- Add cross-references between CSRF and CORS filter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51339">#51339</a>
- Enhance error message when
quarkus.hibernate-search-orm.management.enabled=true is enabled but no
quarkus-vertx-http defined</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51340">#51340</a>
- Fix JavaDoc for quarkus.management.enabled</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51341">#51341</a>
- Use correct name for <code>org.graalvm.sdk:nativebridge</code>
dependency</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51344">#51344</a>
- Set expiresIn to one hour for OIDC Dev Services</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51345">#51345</a>
- extraneous semicolon in LGTM starter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51346">#51346</a>
- Bump the hibernate group with 9 updates</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51352">#51352</a>
- Bump org.quartz-scheduler:quartz from 2.5.0 to 2.5.2</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51358">#51358</a>
- Bump Keycloak version to 26.4.7</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51361">#51361</a>
- Remove extraneous semicolon in LGTM codestart</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51370">#51370</a>
- Add documentation about <code>@JsonView</code> support in the REST
Client</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51372">#51372</a>
- Make token expiration configurable for OIDC Dev Services</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51375">#51375</a>
- Config relocation mp.messaging -&gt; quarkus.messaging
relocation/fallback</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51376">#51376</a>
- Bump kafka.version from 4.0.1 to 4.1.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51377">#51377</a>
- Enhance docs for quarkus.debug.reflection option</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51378">#51378</a>
- QuarkusComponentTest fails with ambiguous dependencies if bean is
injected with parameterized qualifier multiple times</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51379">#51379</a>
- Check that Vert.x HTTP is available before enabling Hibernate Search
management endpoints</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51380">#51380</a>
- Clear some internal state of REST Assured between tests</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51394">#51394</a>
- Make container-image.tag optional so it is possible to nullify it</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51399">#51399</a>
- Fix LogRuntimeConfig doc rendering</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51408">#51408</a>
- Lambda extension: Failed to start quarkus because of
NoSuchMethodError</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/27d19efa3fc61601205bdef56123862e29ef8566"><code>27d19ef</code></a>
[RELEASE] - Bump version to 3.30.4</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/e3f096fb3cf74bebc7eb4ff220c95480a3309f04"><code>e3f096f</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/51588">#51588</a>
from gsmet/3.30.4-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/a229f483aee508b81268c12357e445ceba990985"><code>a229f48</code></a>
Bump to Vert.x 4.5.23 and Netty 4.1.130.Final</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/ea8b668466095ba0753067145c120dbf59d5d34a"><code>ea8b668</code></a>
Bump to Mutiny 3.1.0 and Mutiny Vert.x bindings 3.21.1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/993f47f644c629cb30f5589f3dfce1a631acbb72"><code>993f47f</code></a>
No longer need to disable JBoss Threads logging of version</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/51b52ebd6bad8f75bd190e3800874cfec3411e2c"><code>51b52eb</code></a>
Upgrade to JBoss Threads 3.9.2</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/eba293febde2c943bd64d0363b749b777e8ff1e9"><code>eba293f</code></a>
feat(oidc): fix issuer-based tenant resulition for local issuers</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/80a9a9b8e3e3866ee8f994479b08566e4244e61a"><code>80a9a9b</code></a>
Remove unneeded vertx-http.</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/878e383f416dabe4f5a1ed791e9fe1983f4f911b"><code>878e383</code></a>
Upgrade LGTM to 0.11.17</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/61766a77f60f10a86220188fa7017eee070694bc"><code>61766a7</code></a>
Update RESTEasy to 6.2.15.Final</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.30.2...3.30.4">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>